Proxy:
  Enable: false
  url: http://127.0.0.1:443

Scraper:
  javbus:
    domain: www.javbus.com
  busdmm:
    domain: www.busdmm.ink
  dmmsee:
    domain: www.dmmsee.bond

Source:
  missav:
    domain: missav.ai
    weight: 1000
    cookie:
  jable:
    domain: jable.tv
    weight: 800
    cookie:
  hohoj:
    domain: hohoj.tv
    weight: 700
  memo:
    domain: memojav.com
    weight: 600
  kanav:
    domain: kanav.info
    weight: 500
  avtoday:
    domain: avtoday.io
    weight: 400
  netflav:
    domain: netflav.com
    weight: 300
  kissav:
    domain: f15.bzraizy.cc
    weight: 200
