Proxy:
  Enable: false
  url: http://127.0.0.1:443

UrlPrefix: null

Scraper:
  javbus:
    domain: www.javbus.com
  busdmm:
    domain: www.busdmm.ink
  dmmsee:
    domain: www.dmmsee.bond

Source:
  missav:
    domain: missav.ai
    weight: 1000
  jable:
    domain: jable.tv
    weight: 800
  memo:
    domain: memojav.com
    weight: 600
