[project]
name = "nassav"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "curl-cffi>=0.10.0",
    "loguru>=0.7.3",
    "pillow>=11.1.0",
    "pip>=25.3",
]
